/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_pwm.h"
#include "fsl_lpuart.h"
#include "fsl_clock.h"
#include "fsl_ctimer.h"
#include "fsl_gpio.h"
#include "fsl_port.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Definition of peripheral ID */
#define FLEXPWM0_PERIPHERAL FLEXPWM0
/* Definition of submodule 0 ID */
#define FLEXPWM0_STICK kPWM_Module_0
/* Definition of clock source of submodule 0 frequency in Hertz */
#define FLEXPWM0_STICK_SM_CLK_SOURCE_FREQ_HZ 96000000U
/* Definition of submodule 0 counter clock source frequency in Hertz - FLEXPWM0_STICK_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define FLEXPWM0_STICK_COUNTER_CLK_SOURCE_FREQ_HZ 750000U
/* Definition of submodule 0 counter (PWM) frequency in Hertz */
#define FLEXPWM0_STICK_COUNTER_FREQ_HZ 15U
/* Definition of submodule 0 channel A ID */
#define FLEXPWM0_STICK_A kPWM_PwmA
/* Definition of submodule 0 channel B ID */
#define FLEXPWM0_STICK_B kPWM_PwmB
/* Definition of submodule 0 channel X ID */
#define FLEXPWM0_STICK_X kPWM_PwmX
/* FLEXPWM0 interrupt vector ID (number). */
#define FLEXPWM0_COMMON_SM_0_IRQN FLEXPWM0_SUBMODULE0_IRQn
/* FLEXPWM0 interrupt handler identifier. */
#define PWM_STICK_ISR FLEXPWM0_SUBMODULE0_IRQHandler
/* Definition of submodule 1 ID */
#define FLEXPWM0_AXIS kPWM_Module_1
/* Definition of clock source of submodule 1 frequency in Hertz */
#define FLEXPWM0_AXIS_SM_CLK_SOURCE_FREQ_HZ 96000000U
/* Definition of submodule 1 counter clock source frequency in Hertz - FLEXPWM0_AXIS_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define FLEXPWM0_AXIS_COUNTER_CLK_SOURCE_FREQ_HZ 750000U
/* Definition of submodule 1 counter (PWM) frequency in Hertz */
#define FLEXPWM0_AXIS_COUNTER_FREQ_HZ 15U
/* Definition of submodule 1 channel A ID */
#define FLEXPWM0_AXIS_A kPWM_PwmA
/* Definition of submodule 1 channel B ID */
#define FLEXPWM0_AXIS_B kPWM_PwmB
/* Definition of submodule 1 channel X ID */
#define FLEXPWM0_AXIS_X kPWM_PwmX
/* FLEXPWM0 interrupt vector ID (number). */
#define FLEXPWM0_COMMON_SM_1_IRQN FLEXPWM0_SUBMODULE1_IRQn
/* FLEXPWM0 interrupt handler identifier. */
#define PWM_AXIS_ISR FLEXPWM0_SUBMODULE1_IRQHandler
/* Definition of submodule 2 ID */
#define FLEXPWM0_TOWER kPWM_Module_2
/* Definition of clock source of submodule 2 frequency in Hertz */
#define FLEXPWM0_TOWER_SM_CLK_SOURCE_FREQ_HZ 96000000U
/* Definition of submodule 2 counter clock source frequency in Hertz - FLEXPWM0_TOWER_SM_CLK_SOURCE_FREQ_HZ divided by prescaler */
#define FLEXPWM0_TOWER_COUNTER_CLK_SOURCE_FREQ_HZ 750000U
/* Definition of submodule 2 counter (PWM) frequency in Hertz */
#define FLEXPWM0_TOWER_COUNTER_FREQ_HZ 15U
/* Definition of submodule 2 channel A ID */
#define FLEXPWM0_TOWER_A kPWM_PwmA
/* Definition of submodule 2 channel B ID */
#define FLEXPWM0_TOWER_B kPWM_PwmB
/* Definition of submodule 2 channel X ID */
#define FLEXPWM0_TOWER_X kPWM_PwmX
/* FLEXPWM0 interrupt vector ID (number). */
#define FLEXPWM0_COMMON_SM_2_IRQN FLEXPWM0_SUBMODULE2_IRQn
/* FLEXPWM0 interrupt handler identifier. */
#define PWM_TOWER_ISR FLEXPWM0_SUBMODULE2_IRQHandler
/* Definition of fault Fault0 ID */
#define FLEXPWM0_F0_FAULT0 kPWM_Fault_0
/* Definition of fault Fault1 ID */
#define FLEXPWM0_F0_FAULT1 kPWM_Fault_1
/* Definition of fault Fault2 ID */
#define FLEXPWM0_F0_FAULT2 kPWM_Fault_2
/* Definition of fault Fault3 ID */
#define FLEXPWM0_F0_FAULT3 kPWM_Fault_3
/* Definition of peripheral ID */
#define LPUART2_PERIPHERAL LPUART2
/* Definition of the clock source frequency */
#define LPUART2_CLOCK_SOURCE 12000000UL
/* Definition of peripheral ID */
#define CTIMER0_PERIPHERAL CTIMER0
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER0_TICK_FREQ 12000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER0_TICK_PERIOD 83UL
/* Definition of PWM period channel. */
#define CTIMER0_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER0_MATCH_0_CHANNEL kCTIMER_Match_0
/* Definition of channel 1 ID */
#define CTIMER0_MATCH_1_CHANNEL kCTIMER_Match_1
/* CTIMER0 interrupt vector ID (number). */
#define CTIMER0_TIMER_IRQN CTIMER0_IRQn
/* Definition of peripheral ID */
#define CTIMER1_PERIPHERAL CTIMER1
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER1_TICK_FREQ 12000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER1_TICK_PERIOD 83UL
/* Definition of PWM period channel. */
#define CTIMER1_PWM_PERIOD_CH kCTIMER_Match_1
/* Definition of PWM period */
#define CTIMER1_PWM_PERIOD 2665
/* Definition of channel 0 ID */
#define CTIMER1_PWM_TIMER_CHANNEL kCTIMER_Match_0
/* Definition of channel 0 duty */
#define CTIMER1_PWM_TIMER_DUTY 1466
/* CTIMER1 interrupt vector ID (number). */
#define CTIMER1_TIMER_IRQN CTIMER1_IRQn
/* Alias for GPIO1 peripheral */
#define GPIO1_GPIO GPIO1
/* Alias for PORT1 */
#define GPIO1_PORT PORT1
/* GPIO1 interrupt vector ID (number). */
#define GPIO1_IRQN GPIO1_IRQn
/* GPIO1 interrupt handler identifier. */
#define GPIO1_IRQHANDLER GPIO1_IRQHandler
/* Definition of peripheral ID */
#define CTIMER2_PERIPHERAL CTIMER2
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER2_TICK_FREQ 12000000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER2_TICK_PERIOD 83UL
/* Definition of PWM period channel. */
#define CTIMER2_PWM_PERIOD_CH kCTIMER_Match_0
/* Definition of channel 0 ID */
#define CTIMER2_MATCH_0_CHANNEL kCTIMER_Match_0
/* CTIMER2 interrupt vector ID (number). */
#define CTIMER2_TIMER_IRQN CTIMER2_IRQn
/* Alias for GPIO2 peripheral */
#define GPIO2_GPIO GPIO2
/* Alias for PORT2 */
#define GPIO2_PORT PORT2
/* GPIO2 interrupt vector ID (number). */
#define GPIO2_IRQN GPIO2_IRQn
/* GPIO2 interrupt handler identifier. */
#define GPIO2_IRQHANDLER GPIO2_IRQHandler
/* Definition of peripheral ID */
#define LPUART1_PERIPHERAL LPUART1
/* Definition of the clock source frequency */
#define LPUART1_CLOCK_SOURCE 24000000UL
/* Rx transfer buffer size. */
#define LPUART1_RX_BUFFER_SIZE 550
/* LPUART1 interrupt vector ID (number). */
#define LPUART1_IRQN LPUART1_IRQn

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern pwm_config_t FLEXPWM0_STICK_config;

extern pwm_signal_param_t FLEXPWM0_STICK_pwm_function_config[1];
extern pwm_config_t FLEXPWM0_AXIS_config;

extern pwm_signal_param_t FLEXPWM0_AXIS_pwm_function_config[1];
extern pwm_config_t FLEXPWM0_TOWER_config;

extern pwm_signal_param_t FLEXPWM0_TOWER_pwm_function_config[1];
extern const pwm_fault_input_filter_param_t FLEXPWM0_faultInputFilter_config;
extern const pwm_fault_param_t FLEXPWM0_Fault0_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault1_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault2_fault_config;
extern const pwm_fault_param_t FLEXPWM0_Fault3_fault_config;
extern const lpuart_config_t LPUART2_config;
extern const ctimer_config_t CTIMER0_config;
extern const ctimer_match_config_t CTIMER0_Match_0_config;
extern const ctimer_match_config_t CTIMER0_Match_1_config;
extern const ctimer_config_t CTIMER1_config;
extern const ctimer_config_t CTIMER2_config;
extern const ctimer_match_config_t CTIMER2_Match_0_config;
extern const lpuart_config_t LPUART1_config;
extern lpuart_handle_t LPUART1_handle;
extern uint8_t LPUART1_rxBuffer[LPUART1_RX_BUFFER_SIZE];
extern lpuart_transfer_t LPUART1_rxTransfer;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
  /* Single callback function declaration */
extern void TIME_REQUEST_Callback(uint32_t flags);
extern ctimer_callback_t CTIMER0_callback[];
  /* Single callback function declaration */
extern void PWM_TIMER_CALLBACK(uint32_t flags);
extern ctimer_callback_t CTIMER1_callback[];
  /* Single callback function declaration */
extern void TIMER2_CALLBACK_RAMPE(uint32_t flags);
extern ctimer_callback_t CTIMER2_callback[];
/* LPUART transfer callback function for the LPUART1 component (init. function BOARD_InitPeripherals)*/
extern void UART_GPS_Callback(LPUART_Type *base, lpuart_handle_t *handle, status_t status, void *userData);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
