/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORT3_6 (number 44), P3_6/J3[15]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_PWM_PWM_STICK_OUT_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define INIT_PWM_PWM_STICK_OUT_PIN 6U                   /*!<@brief PORT pin number */
#define INIT_PWM_PWM_STICK_OUT_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT3_8 (number 42), P3_8/J3[11]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_PWM_PWM_AXIS_OUT_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define INIT_PWM_PWM_AXIS_OUT_PIN 8U                   /*!<@brief PORT pin number */
#define INIT_PWM_PWM_AXIS_OUT_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PORT3_10 (number 40), P3_10/J3[7]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_PWM_PWM_TOWER_OUT_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define INIT_PWM_PWM_TOWER_OUT_PIN 10U                   /*!<@brief PORT pin number */
#define INIT_PWM_PWM_TOWER_OUT_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Init_PWM(void);

/*! @name PORT1_4 (number 62), P1_4/J2[1]/J1[2]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_UART_UART_2_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define INIT_UART_UART_2_RX_PIN 4U                   /*!<@brief PORT pin number */
#define INIT_UART_UART_2_RX_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT1_5 (number 63), P1_5/J2[3]/J1[4]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_UART_UART_2_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define INIT_UART_UART_2_TX_PIN 5U                   /*!<@brief PORT pin number */
#define INIT_UART_UART_2_TX_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT1_9 (number 3), P1_9/J2[20]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_UART_UART_1_TX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define INIT_UART_UART_1_TX_PIN 9U                   /*!<@brief PORT pin number */
#define INIT_UART_UART_1_TX_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORT1_8 (number 2), P1_8/J2[18]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_UART_UART_1_RX_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define INIT_UART_UART_1_RX_PIN 8U                   /*!<@brief PORT pin number */
#define INIT_UART_UART_1_RX_PIN_MASK (1U << 8U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Init_UART(void);

/*! @name PORT0_16 (number 54), P0_16/J20/U8[1]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_CTIMER0_UART_PAUSE_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define INIT_CTIMER0_UART_PAUSE_PIN 16U                   /*!<@brief PORT pin number */
#define INIT_CTIMER0_UART_PAUSE_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT0_3 (number 52), P0_3/J25[1]/J18[8]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_CTIMER0_DEBUG_UART_TX_PORT PORT0               /*!<@brief PORT peripheral base pointer */
#define INIT_CTIMER0_DEBUG_UART_TX_PIN 3U                   /*!<@brief PORT pin number */
#define INIT_CTIMER0_DEBUG_UART_TX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Init_CTIMER0(void);

/*! @name PORT2_0 (number 14), P2_0/J4[8]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_CTIMER2_RAMP_COUNTER_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define INIT_CTIMER2_RAMP_COUNTER_PIN 0U                   /*!<@brief PORT pin number */
#define INIT_CTIMER2_RAMP_COUNTER_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Init_CTIMER2(void);

/*! @name PORT1_10 (number 4), P1_10/J4[2]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_HOME_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_HOME_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_HOME_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_HOME_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_HOME_PIN 10U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_HOME_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_12 (number 6), P1_12/J4[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_SW1_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_SW1_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_SW1_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_SW1_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_SW1_PIN 12U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_SW1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_13 (number 7), P1_13/J4[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_SW2_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_SW2_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_SW2_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_SW2_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_SW2_PIN 13U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_SW2_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT3_1 (number 45), P3_1/J1[16]/J6[2]/J7[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_DIR_STICK_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_DIR_STICK_GPIO_PIN 1U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_DIR_STICK_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_DIR_STICK_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_DIR_STICK_PIN 1U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_DIR_STICK_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORT3_14 (number 36), P3_14/J2[4]/J5[3]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_DIR_TOWER_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_DIR_TOWER_GPIO_PIN 14U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_DIR_TOWER_GPIO_PIN_MASK (1U << 14U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_DIR_TOWER_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_DIR_TOWER_PIN 14U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_DIR_TOWER_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT3_15 (number 35), P3_15/J2[2]/J5[4]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_DIR_CLEAR_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_DIR_CLEAR_GPIO_PIN 15U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_DIR_CLEAR_GPIO_PIN_MASK (1U << 15U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_DIR_CLEAR_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_DIR_CLEAR_PIN 15U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_DIR_CLEAR_PIN_MASK (1U << 15U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORT2_6 (number 20), P2_6/J2[6]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_ENDSTOP_STICK_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_ENDSTOP_STICK_GPIO_PIN 6U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_ENDSTOP_STICK_GPIO_PIN_MASK (1U << 6U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_ENDSTOP_STICK_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_ENDSTOP_STICK_PIN 6U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_ENDSTOP_STICK_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT2_12 (number 22), P2_12/J2[12]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_ENDSTOP_AXIS_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_ENDSTOP_AXIS_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_ENDSTOP_AXIS_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_ENDSTOP_AXIS_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_ENDSTOP_AXIS_PIN 12U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_ENDSTOP_AXIS_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                                 /* @} */

/*! @name PORT2_13 (number 23), P2_13/J2[8]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_ENDSTOP_TOWER_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_ENDSTOP_TOWER_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_ENDSTOP_TOWER_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_ENDSTOP_TOWER_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_ENDSTOP_TOWER_PIN 13U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_ENDSTOP_TOWER_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT2_16 (number 24), P2_16/J2[10]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_GPIO GPIO2                /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_GPIO_PIN 16U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_PORT PORT2                /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_PIN 16U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                                  /* @} */

/*! @name PORT2_3 (number 17), P2_3/J2[5]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_DIR_STOP_PIN_DIR_AXIS_GPIO GPIO2               /*!<@brief GPIO peripheral base pointer */
#define INIT_DIR_STOP_PIN_DIR_AXIS_GPIO_PIN 3U              /*!<@brief GPIO pin number */
#define INIT_DIR_STOP_PIN_DIR_AXIS_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_DIR_STOP_PIN_DIR_AXIS_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define INIT_DIR_STOP_PIN_DIR_AXIS_PIN 3U                   /*!<@brief PORT pin number */
#define INIT_DIR_STOP_PIN_DIR_AXIS_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Init_DIR_STOP_PIN(void);

/*! @name PORT2_4 (number 18), P2_4/J1[6]/J7[12]
  @{ */

/* Symbols to be used with PORT driver */
#define INIT_CTIMER1_PWM_CLEAR_OUT_PORT PORT2               /*!<@brief PORT peripheral base pointer */
#define INIT_CTIMER1_PWM_CLEAR_OUT_PIN 4U                   /*!<@brief PORT pin number */
#define INIT_CTIMER1_PWM_CLEAR_OUT_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Init_CTIMER1(void);

/*! @name PORT3_12 (number 38), P3_12/J1[12]/J5[1]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_STATUS_LED_LED_RED_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define INIT_STATUS_LED_LED_RED_GPIO_PIN 12U              /*!<@brief GPIO pin number */
#define INIT_STATUS_LED_LED_RED_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_STATUS_LED_LED_RED_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define INIT_STATUS_LED_LED_RED_PIN 12U                   /*!<@brief PORT pin number */
#define INIT_STATUS_LED_LED_RED_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PORT3_13 (number 37), P3_13/J1[14]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_STATUS_LED_LED_GREEN_GPIO GPIO3                /*!<@brief GPIO peripheral base pointer */
#define INIT_STATUS_LED_LED_GREEN_GPIO_PIN 13U              /*!<@brief GPIO pin number */
#define INIT_STATUS_LED_LED_GREEN_GPIO_PIN_MASK (1U << 13U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_STATUS_LED_LED_GREEN_PORT PORT3                /*!<@brief PORT peripheral base pointer */
#define INIT_STATUS_LED_LED_GREEN_PIN 13U                   /*!<@brief PORT pin number */
#define INIT_STATUS_LED_LED_GREEN_PIN_MASK (1U << 13U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORT3_0 (number 46), P3_0/J1[8]
  @{ */

/* Symbols to be used with GPIO driver */
#define INIT_STATUS_LED_LED_BLUE_GPIO GPIO3               /*!<@brief GPIO peripheral base pointer */
#define INIT_STATUS_LED_LED_BLUE_GPIO_PIN 0U              /*!<@brief GPIO pin number */
#define INIT_STATUS_LED_LED_BLUE_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define INIT_STATUS_LED_LED_BLUE_PORT PORT3               /*!<@brief PORT peripheral base pointer */
#define INIT_STATUS_LED_LED_BLUE_PIN 0U                   /*!<@brief PORT pin number */
#define INIT_STATUS_LED_LED_BLUE_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Init_STATUS_LED(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Init_I2C(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
