/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: MCXA153
package_id: MCXA153VLH
mcu_data: ksdk2_0
processor_version: 15.0.0
board: FRDM-MCXA153
external_user_signals: {}
pin_labels:
- {pin_num: '1', pin_signal: P1_7/WUU0_IN9/TRIG_OUT2/LPUART2_CTS_B/CT_INP7/ADC0_A23, label: 'P1_7/J1[1]', identifier: SW3;HOMING}
- {pin_num: '2', pin_signal: P1_8/WUU0_IN10/LPUART1_RXD/LPI2C0_SDA/CT_INP8/CT0_MAT2/I3C0_SDA, label: 'P1_8/J2[18]', identifier: UART_1_RX}
- {pin_num: '3', pin_signal: P1_9/LPUART1_TXD/LPI2C0_SCL/CT_INP9/CT0_MAT3/I3C0_SCL, label: 'P1_9/J2[20]', identifier: UART_1_TX}
- {pin_num: '4', pin_signal: P1_10/LPUART1_RTS_B/LPI2C0_SDAS/CT2_MAT0/ADC0_A8, label: 'P1_10/J4[2]', identifier: PWM_DIR_2;PWM_DIR_TEST;Home;HOME}
- {pin_num: '5', pin_signal: P1_11/WUU0_IN11/TRIG_OUT2/LPUART1_CTS_B/LPI2C0_SCLS/CT2_MAT1/I3C0_PUR/ADC0_A9, label: 'P1_11/TP5/J4[9]', identifier: HOMING_TEST}
- {pin_num: '6', pin_signal: P1_12/WUU0_IN12/LPUART2_RXD/CT2_MAT2/ADC0_A10, label: 'P1_12/J4[4]', identifier: PWM_DIR_3;SW1}
- {pin_num: '7', pin_signal: P1_13/TRIG_IN3/LPUART2_TXD/CT2_MAT3/ADC0_A11, label: 'P1_13/J4[6]', identifier: PWM_DIR_;PWM_DIR_1;SW2}
- {pin_num: '14', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/CT_INP16/CT2_MAT0/ADC0_A0, label: 'P2_0/J4[8]', identifier: PWM_DIR_0;RAMP_COUNTER}
- {pin_num: '17', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/ADC0_A2/CMP1_IN0, label: 'P2_3/J2[5]', identifier: DIR_AXIS}
- {pin_num: '18', pin_signal: P2_4/CT_INP14/CT1_MAT0, label: 'P2_4/J1[6]/J7[12]', identifier: ENDSTOP_2;PWM;PWM_CLEAR_OUT}
- {pin_num: '19', pin_signal: P2_5/CT_INP15/CT1_MAT1, label: 'P2_5/J1[10]/J5[2]', identifier: ENDSTOP_1}
- {pin_num: '20', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/CT_INP18/CT1_MAT2/ADC0_A3, label: 'P2_6/J2[6]', identifier: ENDSTOP_0;ENDSTOP_STICK}
- {pin_num: '22', pin_signal: P2_12/WUU0_IN20/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT0_MAT0/ADC0_A5, label: 'P2_12/J2[12]', identifier: ENDSTOP_1;ENDSTOP_AXIS}
- {pin_num: '23', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT0_MAT1, label: 'P2_13/J2[8]', identifier: ENDSTOP_TOWER}
- {pin_num: '24', pin_signal: P2_16/LPSPI1_SDI/LPUART1_RTS_B/CT0_MAT2/ADC0_A6, label: 'P2_16/J2[10]', identifier: ENDSTOP_CLEAR}
- {pin_num: '35', pin_signal: P3_15/LPUART2_TXD/CT_INP7, label: 'P3_15/J2[2]/J5[4]', identifier: ENDSTOP_3;DIR_3;DIR_CLEAR}
- {pin_num: '36', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/CT_INP6/PWM0_X2, label: 'P3_14/J2[4]/J5[3]', identifier: DIR_2;DIR_AXIS;DIR_TOWER}
- {pin_num: '40', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2, label: 'P3_10/J3[7]', identifier: PWM_A_2_PIN;PWM_AXIS_PIN;PWM_TOWER_PIN;PWM_TOWER_OUT}
- {pin_num: '42', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/CLKOUT, label: 'P3_8/J3[11]', identifier: PWM_A_1_PIN;PWM_TOWER_PIN;PWM_AXIS_PIN;PWM_AXIS_OUT}
- {pin_num: '44', pin_signal: P3_6/CLKOUT/LPSPI1_PCS3/PWM0_A0/FREQME_CLK_OUT1, label: 'P3_6/J3[15]', identifier: PWM_A_0_PIN;PWM_A_STICK_PIN;PW_STICK_PIN;PWM_STICK_PIN;PWM_STICK_OUT}
- {pin_num: '45', pin_signal: P3_1/TRIG_IN1/CT_INP17/PWM0_B0/FREQME_CLK_OUT0, label: 'P3_1/J1[16]/J6[2]/J7[10]', identifier: ENDSTOP_0;DIR_0;DIR_STICK}
- {pin_num: '54', pin_signal: P0_16/WUU0_IN2/LPI2C0_SDA/LPSPI0_PCS2/CT0_MAT0/UTICK_CAP2/I3C0_SDA, label: 'P0_16/J20/U8[1]', identifier: UART_PAUSE}
- {pin_num: '62', pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/ADC0_A20/CMP0_IN2, label: 'P1_4/J2[1]/J1[2]', identifier: UART_2_RX}
- {pin_num: '63', pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/ADC0_A21/CMP1_IN2, label: 'P1_5/J2[3]/J1[4]', identifier: UART_2_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    Init_PWM();
    Init_UART();
    Init_CTIMER0();
    Init_CTIMER2();
    Init_DIR_STOP_PIN();
    Init_CTIMER1();
    Init_STATUS_LED();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Init_PWM:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '44', peripheral: FlexPWM0, signal: 'A, 0', pin_signal: P3_6/CLKOUT/LPSPI1_PCS3/PWM0_A0/FREQME_CLK_OUT1, identifier: PWM_STICK_OUT, slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '42', peripheral: FlexPWM0, signal: 'A, 1', pin_signal: P3_8/WUU0_IN23/TRIG_IN3/LPSPI1_SDO/LPUART1_RXD/CT_INP4/PWM0_A1/CLKOUT, identifier: PWM_AXIS_OUT,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '40', peripheral: FlexPWM0, signal: 'A, 2', pin_signal: P3_10/TRIG_IN5/LPSPI1_SCK/LPUART1_RTS_B/CT1_MAT0/PWM0_A2, identifier: PWM_TOWER_OUT, slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Init_PWM
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Init_PWM(void)
{
    /* Write to PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* FLEXPWM0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kFLEXPWM0_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    const port_pin_config_t PWM_TOWER_OUT = {/* Internal pull-up/down resistor is disabled */
                                             kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             kPORT_LowDriveStrength,
                                             /* Normal drive strength is configured */
                                             kPORT_NormalDriveStrength,
                                             /* Pin is configured as PWM0_A2 */
                                             kPORT_MuxAlt5,
                                             /* Digital input enabled */
                                             kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             kPORT_UnlockRegister};
    /* PORT3_10 (pin 40) is configured as PWM0_A2 */
    PORT_SetPinConfig(INIT_PWM_PWM_TOWER_OUT_PORT, INIT_PWM_PWM_TOWER_OUT_PIN, &PWM_TOWER_OUT);

    const port_pin_config_t PWM_STICK_OUT = {/* Internal pull-up/down resistor is disabled */
                                             kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             kPORT_LowDriveStrength,
                                             /* Normal drive strength is configured */
                                             kPORT_NormalDriveStrength,
                                             /* Pin is configured as PWM0_A0 */
                                             kPORT_MuxAlt5,
                                             /* Digital input enabled */
                                             kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             kPORT_UnlockRegister};
    /* PORT3_6 (pin 44) is configured as PWM0_A0 */
    PORT_SetPinConfig(INIT_PWM_PWM_STICK_OUT_PORT, INIT_PWM_PWM_STICK_OUT_PIN, &PWM_STICK_OUT);

    const port_pin_config_t PWM_AXIS_OUT = {/* Internal pull-up/down resistor is disabled */
                                            kPORT_PullDisable,
                                            /* Low internal pull resistor value is selected. */
                                            kPORT_LowPullResistor,
                                            /* Fast slew rate is configured */
                                            kPORT_FastSlewRate,
                                            /* Passive input filter is disabled */
                                            kPORT_PassiveFilterDisable,
                                            /* Open drain output is disabled */
                                            kPORT_OpenDrainDisable,
                                            /* Low drive strength is configured */
                                            kPORT_LowDriveStrength,
                                            /* Normal drive strength is configured */
                                            kPORT_NormalDriveStrength,
                                            /* Pin is configured as PWM0_A1 */
                                            kPORT_MuxAlt5,
                                            /* Digital input enabled */
                                            kPORT_InputBufferEnable,
                                            /* Digital input is not inverted */
                                            kPORT_InputNormal,
                                            /* Pin Control Register fields [15:0] are not locked */
                                            kPORT_UnlockRegister};
    /* PORT3_8 (pin 42) is configured as PWM0_A1 */
    PORT_SetPinConfig(INIT_PWM_PWM_AXIS_OUT_PORT, INIT_PWM_PWM_AXIS_OUT_PIN, &PWM_AXIS_OUT);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Init_UART:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '62', peripheral: LPUART2, signal: RX, pin_signal: P1_4/WUU0_IN8/FREQME_CLK_IN0/LPSPI0_PCS3/LPUART2_RXD/CT1_MAT2/ADC0_A20/CMP0_IN2, slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: '63', peripheral: LPUART2, signal: TX, pin_signal: P1_5/FREQME_CLK_IN1/LPSPI0_PCS2/LPUART2_TXD/CT1_MAT3/ADC0_A21/CMP1_IN2, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: up, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: '3', peripheral: LPUART1, signal: TX, pin_signal: P1_9/LPUART1_TXD/LPI2C0_SCL/CT_INP9/CT0_MAT3/I3C0_SCL, slew_rate: fast, open_drain: disable, drive_strength: low,
    extra_drive_strength: normal, pull_select: up, pull_enable: enable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '2', peripheral: LPUART1, signal: RX, pin_signal: P1_8/WUU0_IN10/LPUART1_RXD/LPI2C0_SDA/CT_INP8/CT0_MAT2/I3C0_SDA, slew_rate: fast, open_drain: disable,
    drive_strength: low, extra_drive_strength: normal, pull_select: up, pull_enable: enable, passive_filter: disable, pull_value: low, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Init_UART
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Init_UART(void)
{
    /* Write to PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* LPUART2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART2_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* LPUART1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kLPUART1_RST_SHIFT_RSTn);

    const port_pin_config_t UART_2_RX = {/* Internal pull-up resistor is enabled */
                                         kPORT_PullUp,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as LPUART2_RXD */
                                         kPORT_MuxAlt3,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT1_4 (pin 62) is configured as LPUART2_RXD */
    PORT_SetPinConfig(INIT_UART_UART_2_RX_PORT, INIT_UART_UART_2_RX_PIN, &UART_2_RX);

    const port_pin_config_t UART_2_TX = {/* Internal pull-up resistor is enabled */
                                         kPORT_PullUp,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as LPUART2_TXD */
                                         kPORT_MuxAlt3,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT1_5 (pin 63) is configured as LPUART2_TXD */
    PORT_SetPinConfig(INIT_UART_UART_2_TX_PORT, INIT_UART_UART_2_TX_PIN, &UART_2_TX);

    const port_pin_config_t UART_1_RX = {/* Internal pull-up resistor is enabled */
                                         kPORT_PullUp,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as LPUART1_RXD */
                                         kPORT_MuxAlt2,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT1_8 (pin 2) is configured as LPUART1_RXD */
    PORT_SetPinConfig(INIT_UART_UART_1_RX_PORT, INIT_UART_UART_1_RX_PIN, &UART_1_RX);

    const port_pin_config_t UART_1_TX = {/* Internal pull-up resistor is enabled */
                                         kPORT_PullUp,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as LPUART1_TXD */
                                         kPORT_MuxAlt2,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT1_9 (pin 3) is configured as LPUART1_TXD */
    PORT_SetPinConfig(INIT_UART_UART_1_TX_PORT, INIT_UART_UART_1_TX_PIN, &UART_1_TX);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Init_CTIMER0:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '54', peripheral: CTIMER0, signal: 'MATCH, 0', pin_signal: P0_16/WUU0_IN2/LPI2C0_SDA/LPSPI0_PCS2/CT0_MAT0/UTICK_CAP2/I3C0_SDA, slew_rate: fast, open_drain: disable,
    drive_strength: low, extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, pull_value: low, input_buffer: enable, invert_input: normal}
  - {pin_num: '52', peripheral: CTIMER0, signal: 'MATCH, 1', pin_signal: P0_3/TDI/LPUART0_TXD/LPSPI0_SDO/CT0_MAT1/UTICK_CAP1/CMP0_OUT/CMP1_IN1, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Init_CTIMER0
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Init_CTIMER0(void)
{
    /* Write to PORT0: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT0);
    /* CTIMER0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER0_RST_SHIFT_RSTn);
    /* PORT0 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT0_RST_SHIFT_RSTn);

    const port_pin_config_t UART_PAUSE = {/* Internal pull-up/down resistor is disabled */
                                          kPORT_PullDisable,
                                          /* Low internal pull resistor value is selected. */
                                          kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          kPORT_OpenDrainDisable,
                                          /* Low drive strength is configured */
                                          kPORT_LowDriveStrength,
                                          /* Normal drive strength is configured */
                                          kPORT_NormalDriveStrength,
                                          /* Pin is configured as CT0_MAT0 */
                                          kPORT_MuxAlt4,
                                          /* Digital input enabled */
                                          kPORT_InputBufferEnable,
                                          /* Digital input is not inverted */
                                          kPORT_InputNormal,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          kPORT_UnlockRegister};
    /* PORT0_16 (pin 54) is configured as CT0_MAT0 */
    PORT_SetPinConfig(INIT_CTIMER0_UART_PAUSE_PORT, INIT_CTIMER0_UART_PAUSE_PIN, &UART_PAUSE);

    const port_pin_config_t DEBUG_UART_TX = {/* Internal pull-up/down resistor is disabled */
                                             kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             kPORT_LowDriveStrength,
                                             /* Normal drive strength is configured */
                                             kPORT_NormalDriveStrength,
                                             /* Pin is configured as CT0_MAT1 */
                                             kPORT_MuxAlt4,
                                             /* Digital input enabled */
                                             kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             kPORT_UnlockRegister};
    /* PORT0_3 (pin 52) is configured as CT0_MAT1 */
    PORT_SetPinConfig(INIT_CTIMER0_DEBUG_UART_TX_PORT, INIT_CTIMER0_DEBUG_UART_TX_PIN, &DEBUG_UART_TX);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Init_CTIMER2:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '14', peripheral: CTIMER2, signal: 'MATCH, 0', pin_signal: P2_0/WUU0_IN18/TRIG_IN6/LPUART0_RXD/CT_INP16/CT2_MAT0/ADC0_A0, identifier: RAMP_COUNTER,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Init_CTIMER2
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Init_CTIMER2(void)
{
    /* Write to PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* CTIMER2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER2_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    const port_pin_config_t RAMP_COUNTER = {/* Internal pull-up/down resistor is disabled */
                                            kPORT_PullDisable,
                                            /* Low internal pull resistor value is selected. */
                                            kPORT_LowPullResistor,
                                            /* Fast slew rate is configured */
                                            kPORT_FastSlewRate,
                                            /* Passive input filter is disabled */
                                            kPORT_PassiveFilterDisable,
                                            /* Open drain output is disabled */
                                            kPORT_OpenDrainDisable,
                                            /* Low drive strength is configured */
                                            kPORT_LowDriveStrength,
                                            /* Normal drive strength is configured */
                                            kPORT_NormalDriveStrength,
                                            /* Pin is configured as CT2_MAT0 */
                                            kPORT_MuxAlt5,
                                            /* Digital input enabled */
                                            kPORT_InputBufferEnable,
                                            /* Digital input is not inverted */
                                            kPORT_InputNormal,
                                            /* Pin Control Register fields [15:0] are not locked */
                                            kPORT_UnlockRegister};
    /* PORT2_0 (pin 14) is configured as CT2_MAT0 */
    PORT_SetPinConfig(INIT_CTIMER2_RAMP_COUNTER_PORT, INIT_CTIMER2_RAMP_COUNTER_PIN, &RAMP_COUNTER);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Init_DIR_STOP_PIN:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '4', peripheral: GPIO1, signal: 'GPIO, 10', pin_signal: P1_10/LPUART1_RTS_B/LPI2C0_SDAS/CT2_MAT0/ADC0_A8, identifier: HOME, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptRisingEdge,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: '6', peripheral: GPIO1, signal: 'GPIO, 12', pin_signal: P1_12/WUU0_IN12/LPUART2_RXD/CT2_MAT2/ADC0_A10, identifier: SW1, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptRisingEdge,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: '7', peripheral: GPIO1, signal: 'GPIO, 13', pin_signal: P1_13/TRIG_IN3/LPUART2_TXD/CT2_MAT3/ADC0_A11, identifier: SW2, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptRisingEdge,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: enable, input_buffer: enable, invert_input: normal}
  - {pin_num: '45', peripheral: GPIO3, signal: 'GPIO, 1', pin_signal: P3_1/TRIG_IN1/CT_INP17/PWM0_B0/FREQME_CLK_OUT0, identifier: DIR_STICK, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable,
    invert_input: normal}
  - {pin_num: '36', peripheral: GPIO3, signal: 'GPIO, 14', pin_signal: P3_14/WUU0_IN25/LPUART2_RXD/CT_INP6/PWM0_X2, identifier: DIR_TOWER, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '35', peripheral: GPIO3, signal: 'GPIO, 15', pin_signal: P3_15/LPUART2_TXD/CT_INP7, identifier: DIR_CLEAR, direction: OUTPUT, gpio_init_state: 'false',
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '20', peripheral: GPIO2, signal: 'GPIO, 6', pin_signal: P2_6/TRIG_OUT4/LPSPI1_PCS1/CT_INP18/CT1_MAT2/ADC0_A3, identifier: ENDSTOP_STICK, direction: INPUT,
    gpio_per_interrupt: kGPIO_InterruptRisingEdge, slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable,
    invert_input: normal}
  - {pin_num: '22', peripheral: GPIO2, signal: 'GPIO, 12', pin_signal: P2_12/WUU0_IN20/USB0_VBUS_DET/LPSPI1_SCK/LPUART1_RXD/CT0_MAT0/ADC0_A5, identifier: ENDSTOP_AXIS,
    direction: INPUT, gpio_per_interrupt: kGPIO_InterruptRisingEdge, slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable,
    input_buffer: enable, invert_input: normal}
  - {pin_num: '23', peripheral: GPIO2, signal: 'GPIO, 13', pin_signal: P2_13/TRIG_IN8/LPSPI1_SDO/LPUART1_TXD/CT0_MAT1, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptRisingEdge,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '24', peripheral: GPIO2, signal: 'GPIO, 16', pin_signal: P2_16/LPSPI1_SDI/LPUART1_RTS_B/CT0_MAT2/ADC0_A6, direction: INPUT, gpio_per_interrupt: kGPIO_InterruptRisingEdge,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '17', peripheral: GPIO2, signal: 'GPIO, 3', pin_signal: P2_3/WUU0_IN19/TRIG_IN7/LPUART0_CTS_B/LPUART2_RXD/CT_INP13/CT2_MAT3/ADC0_A2/CMP1_IN0, direction: OUTPUT,
    gpio_init_state: 'false', slew_rate: fast, open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Init_DIR_STOP_PIN
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Init_DIR_STOP_PIN(void)
{
    /* Write to GPIO1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO1);
    /* Write to GPIO2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO2);
    /* Write to GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* Write to PORT1: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT1);
    /* Write to PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* Write to PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO1_RST_SHIFT_RSTn);
    /* GPIO2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO2_RST_SHIFT_RSTn);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t HOME_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_10 (pin 4)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_HOME_GPIO, INIT_DIR_STOP_PIN_HOME_PIN, &HOME_config);

    gpio_pin_config_t SW1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_12 (pin 6)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_SW1_GPIO, INIT_DIR_STOP_PIN_SW1_PIN, &SW1_config);

    gpio_pin_config_t SW2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO1_13 (pin 7)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_SW2_GPIO, INIT_DIR_STOP_PIN_SW2_PIN, &SW2_config);

    gpio_pin_config_t DIR_AXIS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_3 (pin 17)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_DIR_AXIS_GPIO, INIT_DIR_STOP_PIN_DIR_AXIS_PIN, &DIR_AXIS_config);

    gpio_pin_config_t ENDSTOP_STICK_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_6 (pin 20)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_ENDSTOP_STICK_GPIO, INIT_DIR_STOP_PIN_ENDSTOP_STICK_PIN, &ENDSTOP_STICK_config);

    gpio_pin_config_t ENDSTOP_AXIS_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_12 (pin 22)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_ENDSTOP_AXIS_GPIO, INIT_DIR_STOP_PIN_ENDSTOP_AXIS_PIN, &ENDSTOP_AXIS_config);

    gpio_pin_config_t ENDSTOP_TOWER_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_13 (pin 23)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_ENDSTOP_TOWER_GPIO, INIT_DIR_STOP_PIN_ENDSTOP_TOWER_PIN, &ENDSTOP_TOWER_config);

    gpio_pin_config_t ENDSTOP_CLEAR_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_16 (pin 24)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_GPIO, INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_PIN, &ENDSTOP_CLEAR_config);

    gpio_pin_config_t DIR_STICK_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_1 (pin 45)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_DIR_STICK_GPIO, INIT_DIR_STOP_PIN_DIR_STICK_PIN, &DIR_STICK_config);

    gpio_pin_config_t DIR_TOWER_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_14 (pin 36)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_DIR_TOWER_GPIO, INIT_DIR_STOP_PIN_DIR_TOWER_PIN, &DIR_TOWER_config);

    gpio_pin_config_t DIR_CLEAR_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_15 (pin 35)  */
    GPIO_PinInit(INIT_DIR_STOP_PIN_DIR_CLEAR_GPIO, INIT_DIR_STOP_PIN_DIR_CLEAR_PIN, &DIR_CLEAR_config);

    /* Interrupt configuration on GPIO1_10 (pin 4): Interrupt on rising edge */
    GPIO_SetPinInterruptConfig(INIT_DIR_STOP_PIN_HOME_GPIO, INIT_DIR_STOP_PIN_HOME_PIN, kGPIO_InterruptRisingEdge);

    /* Interrupt configuration on GPIO1_12 (pin 6): Interrupt on rising edge */
    GPIO_SetPinInterruptConfig(INIT_DIR_STOP_PIN_SW1_GPIO, INIT_DIR_STOP_PIN_SW1_PIN, kGPIO_InterruptRisingEdge);

    /* Interrupt configuration on GPIO1_13 (pin 7): Interrupt on rising edge */
    GPIO_SetPinInterruptConfig(INIT_DIR_STOP_PIN_SW2_GPIO, INIT_DIR_STOP_PIN_SW2_PIN, kGPIO_InterruptRisingEdge);

    /* Interrupt configuration on GPIO2_12 (pin 22): Interrupt on rising edge */
    GPIO_SetPinInterruptConfig(INIT_DIR_STOP_PIN_ENDSTOP_AXIS_GPIO, INIT_DIR_STOP_PIN_ENDSTOP_AXIS_PIN, kGPIO_InterruptRisingEdge);

    /* Interrupt configuration on GPIO2_13 (pin 23): Interrupt on rising edge */
    GPIO_SetPinInterruptConfig(INIT_DIR_STOP_PIN_ENDSTOP_TOWER_GPIO, INIT_DIR_STOP_PIN_ENDSTOP_TOWER_PIN, kGPIO_InterruptRisingEdge);

    /* Interrupt configuration on GPIO2_16 (pin 24): Interrupt on rising edge */
    GPIO_SetPinInterruptConfig(INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_GPIO, INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_PIN, kGPIO_InterruptRisingEdge);

    /* Interrupt configuration on GPIO2_6 (pin 20): Interrupt on rising edge */
    GPIO_SetPinInterruptConfig(INIT_DIR_STOP_PIN_ENDSTOP_STICK_GPIO, INIT_DIR_STOP_PIN_ENDSTOP_STICK_PIN, kGPIO_InterruptRisingEdge);

    const port_pin_config_t HOME = {/* Internal pull-down resistor is enabled */
                                    kPORT_PullDown,
                                    /* Low internal pull resistor value is selected. */
                                    kPORT_LowPullResistor,
                                    /* Fast slew rate is configured */
                                    kPORT_FastSlewRate,
                                    /* Passive input filter is disabled */
                                    kPORT_PassiveFilterDisable,
                                    /* Open drain output is disabled */
                                    kPORT_OpenDrainDisable,
                                    /* Low drive strength is configured */
                                    kPORT_LowDriveStrength,
                                    /* Normal drive strength is configured */
                                    kPORT_NormalDriveStrength,
                                    /* Pin is configured as P1_10 */
                                    kPORT_MuxAlt0,
                                    /* Digital input enabled */
                                    kPORT_InputBufferEnable,
                                    /* Digital input is not inverted */
                                    kPORT_InputNormal,
                                    /* Pin Control Register fields [15:0] are not locked */
                                    kPORT_UnlockRegister};
    /* PORT1_10 (pin 4) is configured as P1_10 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_HOME_PORT, INIT_DIR_STOP_PIN_HOME_PIN, &HOME);

    const port_pin_config_t SW1 = {/* Internal pull-down resistor is enabled */
                                   kPORT_PullDown,
                                   /* Low internal pull resistor value is selected. */
                                   kPORT_LowPullResistor,
                                   /* Fast slew rate is configured */
                                   kPORT_FastSlewRate,
                                   /* Passive input filter is disabled */
                                   kPORT_PassiveFilterDisable,
                                   /* Open drain output is disabled */
                                   kPORT_OpenDrainDisable,
                                   /* Low drive strength is configured */
                                   kPORT_LowDriveStrength,
                                   /* Normal drive strength is configured */
                                   kPORT_NormalDriveStrength,
                                   /* Pin is configured as P1_12 */
                                   kPORT_MuxAlt0,
                                   /* Digital input enabled */
                                   kPORT_InputBufferEnable,
                                   /* Digital input is not inverted */
                                   kPORT_InputNormal,
                                   /* Pin Control Register fields [15:0] are not locked */
                                   kPORT_UnlockRegister};
    /* PORT1_12 (pin 6) is configured as P1_12 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_SW1_PORT, INIT_DIR_STOP_PIN_SW1_PIN, &SW1);

    const port_pin_config_t SW2 = {/* Internal pull-down resistor is enabled */
                                   kPORT_PullDown,
                                   /* Low internal pull resistor value is selected. */
                                   kPORT_LowPullResistor,
                                   /* Fast slew rate is configured */
                                   kPORT_FastSlewRate,
                                   /* Passive input filter is disabled */
                                   kPORT_PassiveFilterDisable,
                                   /* Open drain output is disabled */
                                   kPORT_OpenDrainDisable,
                                   /* Low drive strength is configured */
                                   kPORT_LowDriveStrength,
                                   /* Normal drive strength is configured */
                                   kPORT_NormalDriveStrength,
                                   /* Pin is configured as P1_13 */
                                   kPORT_MuxAlt0,
                                   /* Digital input enabled */
                                   kPORT_InputBufferEnable,
                                   /* Digital input is not inverted */
                                   kPORT_InputNormal,
                                   /* Pin Control Register fields [15:0] are not locked */
                                   kPORT_UnlockRegister};
    /* PORT1_13 (pin 7) is configured as P1_13 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_SW2_PORT, INIT_DIR_STOP_PIN_SW2_PIN, &SW2);

    const port_pin_config_t ENDSTOP_AXIS = {/* Internal pull-up/down resistor is disabled */
                                            kPORT_PullDisable,
                                            /* Low internal pull resistor value is selected. */
                                            kPORT_LowPullResistor,
                                            /* Fast slew rate is configured */
                                            kPORT_FastSlewRate,
                                            /* Passive input filter is disabled */
                                            kPORT_PassiveFilterDisable,
                                            /* Open drain output is disabled */
                                            kPORT_OpenDrainDisable,
                                            /* Low drive strength is configured */
                                            kPORT_LowDriveStrength,
                                            /* Normal drive strength is configured */
                                            kPORT_NormalDriveStrength,
                                            /* Pin is configured as P2_12 */
                                            kPORT_MuxAlt0,
                                            /* Digital input enabled */
                                            kPORT_InputBufferEnable,
                                            /* Digital input is not inverted */
                                            kPORT_InputNormal,
                                            /* Pin Control Register fields [15:0] are not locked */
                                            kPORT_UnlockRegister};
    /* PORT2_12 (pin 22) is configured as P2_12 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_ENDSTOP_AXIS_PORT, INIT_DIR_STOP_PIN_ENDSTOP_AXIS_PIN, &ENDSTOP_AXIS);

    const port_pin_config_t ENDSTOP_TOWER = {/* Internal pull-up/down resistor is disabled */
                                             kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             kPORT_LowDriveStrength,
                                             /* Normal drive strength is configured */
                                             kPORT_NormalDriveStrength,
                                             /* Pin is configured as P2_13 */
                                             kPORT_MuxAlt0,
                                             /* Digital input enabled */
                                             kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             kPORT_UnlockRegister};
    /* PORT2_13 (pin 23) is configured as P2_13 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_ENDSTOP_TOWER_PORT, INIT_DIR_STOP_PIN_ENDSTOP_TOWER_PIN, &ENDSTOP_TOWER);

    const port_pin_config_t ENDSTOP_CLEAR = {/* Internal pull-up/down resistor is disabled */
                                             kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             kPORT_LowDriveStrength,
                                             /* Normal drive strength is configured */
                                             kPORT_NormalDriveStrength,
                                             /* Pin is configured as P2_16 */
                                             kPORT_MuxAlt0,
                                             /* Digital input enabled */
                                             kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             kPORT_UnlockRegister};
    /* PORT2_16 (pin 24) is configured as P2_16 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_PORT, INIT_DIR_STOP_PIN_ENDSTOP_CLEAR_PIN, &ENDSTOP_CLEAR);

    const port_pin_config_t DIR_AXIS = {/* Internal pull-up/down resistor is disabled */
                                        kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        kPORT_NormalDriveStrength,
                                        /* Pin is configured as P2_3 */
                                        kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        kPORT_UnlockRegister};
    /* PORT2_3 (pin 17) is configured as P2_3 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_DIR_AXIS_PORT, INIT_DIR_STOP_PIN_DIR_AXIS_PIN, &DIR_AXIS);

    const port_pin_config_t ENDSTOP_STICK = {/* Internal pull-up/down resistor is disabled */
                                             kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             kPORT_LowDriveStrength,
                                             /* Normal drive strength is configured */
                                             kPORT_NormalDriveStrength,
                                             /* Pin is configured as P2_6 */
                                             kPORT_MuxAlt0,
                                             /* Digital input enabled */
                                             kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             kPORT_UnlockRegister};
    /* PORT2_6 (pin 20) is configured as P2_6 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_ENDSTOP_STICK_PORT, INIT_DIR_STOP_PIN_ENDSTOP_STICK_PIN, &ENDSTOP_STICK);

    const port_pin_config_t DIR_STICK = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P3_1 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT3_1 (pin 45) is configured as P3_1 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_DIR_STICK_PORT, INIT_DIR_STOP_PIN_DIR_STICK_PIN, &DIR_STICK);

    const port_pin_config_t DIR_TOWER = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P3_14 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT3_14 (pin 36) is configured as P3_14 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_DIR_TOWER_PORT, INIT_DIR_STOP_PIN_DIR_TOWER_PIN, &DIR_TOWER);

    const port_pin_config_t DIR_CLEAR = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P3_15 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT3_15 (pin 35) is configured as P3_15 */
    PORT_SetPinConfig(INIT_DIR_STOP_PIN_DIR_CLEAR_PORT, INIT_DIR_STOP_PIN_DIR_CLEAR_PIN, &DIR_CLEAR);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Init_CTIMER1:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '18', peripheral: CTIMER1, signal: 'MATCH, 0', pin_signal: P2_4/CT_INP14/CT1_MAT0, identifier: PWM_CLEAR_OUT, slew_rate: fast, open_drain: disable,
    drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Init_CTIMER1
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Init_CTIMER1(void)
{
    /* Write to PORT2: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT2);
    /* CTIMER1 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kCTIMER1_RST_SHIFT_RSTn);
    /* PORT2 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT2_RST_SHIFT_RSTn);

    const port_pin_config_t PWM_CLEAR_OUT = {/* Internal pull-up/down resistor is disabled */
                                             kPORT_PullDisable,
                                             /* Low internal pull resistor value is selected. */
                                             kPORT_LowPullResistor,
                                             /* Fast slew rate is configured */
                                             kPORT_FastSlewRate,
                                             /* Passive input filter is disabled */
                                             kPORT_PassiveFilterDisable,
                                             /* Open drain output is disabled */
                                             kPORT_OpenDrainDisable,
                                             /* Low drive strength is configured */
                                             kPORT_LowDriveStrength,
                                             /* Normal drive strength is configured */
                                             kPORT_NormalDriveStrength,
                                             /* Pin is configured as CT1_MAT0 */
                                             kPORT_MuxAlt5,
                                             /* Digital input enabled */
                                             kPORT_InputBufferEnable,
                                             /* Digital input is not inverted */
                                             kPORT_InputNormal,
                                             /* Pin Control Register fields [15:0] are not locked */
                                             kPORT_UnlockRegister};
    /* PORT2_4 (pin 18) is configured as CT1_MAT0 */
    PORT_SetPinConfig(INIT_CTIMER1_PWM_CLEAR_OUT_PORT, INIT_CTIMER1_PWM_CLEAR_OUT_PIN, &PWM_CLEAR_OUT);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Init_STATUS_LED:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list:
  - {pin_num: '38', peripheral: GPIO3, signal: 'GPIO, 12', pin_signal: P3_12/LPUART2_RTS_B/CT1_MAT2/PWM0_X0, direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '37', peripheral: GPIO3, signal: 'GPIO, 13', pin_signal: P3_13/LPUART2_CTS_B/CT1_MAT3/PWM0_X1, direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast,
    open_drain: disable, drive_strength: low, pull_select: down, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: '46', peripheral: GPIO3, signal: 'GPIO, 0', pin_signal: P3_0/WUU0_IN22/TRIG_IN0/CT_INP16/PWM0_A0, direction: OUTPUT, gpio_init_state: 'false', slew_rate: fast,
    open_drain: disable, drive_strength: low, extra_drive_strength: normal, pull_select: down, pull_enable: disable, passive_filter: disable, input_buffer: enable,
    invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Init_STATUS_LED
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Init_STATUS_LED(void)
{
    /* Write to GPIO3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GateGPIO3);
    /* Write to PORT3: Peripheral clock is enabled */
    CLOCK_EnableClock(kCLOCK_GatePORT3);
    /* GPIO3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kGPIO3_RST_SHIFT_RSTn);
    /* PORT3 peripheral is released from reset */
    RESET_ReleasePeripheralReset(kPORT3_RST_SHIFT_RSTn);

    gpio_pin_config_t LED_BLUE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_0 (pin 46)  */
    GPIO_PinInit(INIT_STATUS_LED_LED_BLUE_GPIO, INIT_STATUS_LED_LED_BLUE_PIN, &LED_BLUE_config);

    gpio_pin_config_t LED_RED_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_12 (pin 38)  */
    GPIO_PinInit(INIT_STATUS_LED_LED_RED_GPIO, INIT_STATUS_LED_LED_RED_PIN, &LED_RED_config);

    gpio_pin_config_t LED_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_13 (pin 37)  */
    GPIO_PinInit(INIT_STATUS_LED_LED_GREEN_GPIO, INIT_STATUS_LED_LED_GREEN_PIN, &LED_GREEN_config);

    const port_pin_config_t LED_BLUE = {/* Internal pull-up/down resistor is disabled */
                                        kPORT_PullDisable,
                                        /* Low internal pull resistor value is selected. */
                                        kPORT_LowPullResistor,
                                        /* Fast slew rate is configured */
                                        kPORT_FastSlewRate,
                                        /* Passive input filter is disabled */
                                        kPORT_PassiveFilterDisable,
                                        /* Open drain output is disabled */
                                        kPORT_OpenDrainDisable,
                                        /* Low drive strength is configured */
                                        kPORT_LowDriveStrength,
                                        /* Normal drive strength is configured */
                                        kPORT_NormalDriveStrength,
                                        /* Pin is configured as P3_0 */
                                        kPORT_MuxAlt0,
                                        /* Digital input enabled */
                                        kPORT_InputBufferEnable,
                                        /* Digital input is not inverted */
                                        kPORT_InputNormal,
                                        /* Pin Control Register fields [15:0] are not locked */
                                        kPORT_UnlockRegister};
    /* PORT3_0 (pin 46) is configured as P3_0 */
    PORT_SetPinConfig(INIT_STATUS_LED_LED_BLUE_PORT, INIT_STATUS_LED_LED_BLUE_PIN, &LED_BLUE);

    const port_pin_config_t LED_RED = {/* Internal pull-up/down resistor is disabled */
                                       kPORT_PullDisable,
                                       /* Low internal pull resistor value is selected. */
                                       kPORT_LowPullResistor,
                                       /* Fast slew rate is configured */
                                       kPORT_FastSlewRate,
                                       /* Passive input filter is disabled */
                                       kPORT_PassiveFilterDisable,
                                       /* Open drain output is disabled */
                                       kPORT_OpenDrainDisable,
                                       /* Low drive strength is configured */
                                       kPORT_LowDriveStrength,
                                       /* Normal drive strength is configured */
                                       kPORT_NormalDriveStrength,
                                       /* Pin is configured as P3_12 */
                                       kPORT_MuxAlt0,
                                       /* Digital input enabled */
                                       kPORT_InputBufferEnable,
                                       /* Digital input is not inverted */
                                       kPORT_InputNormal,
                                       /* Pin Control Register fields [15:0] are not locked */
                                       kPORT_UnlockRegister};
    /* PORT3_12 (pin 38) is configured as P3_12 */
    PORT_SetPinConfig(INIT_STATUS_LED_LED_RED_PORT, INIT_STATUS_LED_LED_RED_PIN, &LED_RED);

    const port_pin_config_t LED_GREEN = {/* Internal pull-up/down resistor is disabled */
                                         kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         kPORT_NormalDriveStrength,
                                         /* Pin is configured as P3_13 */
                                         kPORT_MuxAlt0,
                                         /* Digital input enabled */
                                         kPORT_InputBufferEnable,
                                         /* Digital input is not inverted */
                                         kPORT_InputNormal,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         kPORT_UnlockRegister};
    /* PORT3_13 (pin 37) is configured as P3_13 */
    PORT_SetPinConfig(INIT_STATUS_LED_LED_GREEN_PORT, INIT_STATUS_LED_LED_GREEN_PIN, &LED_GREEN);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Init_I2C:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true', fullInit: 'true'}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Init_I2C
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Init_I2C(void)
{
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
